server:
  port: ${SERVER_PORT:5206}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:postgres}}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
  jackson:
    time-zone: UTC
  mvc:
    problemdetails:
      enabled: false

springdoc:
  api-docs:
    path: /swagger/v3/api-docs
  swagger-ui:
    path: /swagger

app:
  jwt:
    secret: ${JWT_SECRET:SuperSecretKeyForCidadaoInformaApplication2026}
