FROM maven:3.9.11-eclipse-temurin-21-alpine AS build

WORKDIR /app

COPY pom.xml .
RUN mvn --batch-mode --no-transfer-progress dependency:go-offline

COPY src ./src
RUN mvn --batch-mode --no-transfer-progress package

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build /app/target/hackgov-api-1.0.0-SNAPSHOT.jar app.jar

ENV PORT=80

EXPOSE 80

CMD ["/opt/java/openjdk/bin/java", "-XX:MaxRAMPercentage=75.0", "-jar", "/app/app.jar"]
